import { chromium } from "playwright";
const out = new URL("./out/", import.meta.url).pathname;
const B = "http://localhost:3720";
const browser = await chromium.launch();
const errors = [];
const mk = async (w, locale = "ru-RU") => {
  const ctx = await browser.newContext({ viewport: { width: w, height: 900 }, locale });
  const page = await ctx.newPage();
  page.on("pageerror", (e) => errors.push(`${w} ${e.message}`));
  page.on("console", (m) => m.type() === "error" && errors.push(`${w} ${m.text()}`));
  return page;
};
const shot = async (p, name) => { await p.waitForTimeout(300); await p.screenshot({ path: out + name + ".png", fullPage: true }); const o = await p.evaluate(() => document.documentElement.scrollWidth - innerWidth); console.log(name, o ? `OVERFLOW ${o}` : "ok"); };
const ok = (c, m) => { console.log(c ? "  ✓" : "  ✗", m); if (!c) errors.push(m); };

const a = await mk(390);
await a.goto(B + "/brand", { waitUntil: "networkidle" });
await shot(a, "b-390-brand-guest");
await a.getByRole("link", { name: /Войдите, чтобы оставить заявку/ }).click();
await a.getByRole("button", { name: /Ани/ }).click();
await a.waitForURL(/\/brand$/);
await a.getByLabel("Бренд").fill("Ani Bakery");
await a.getByLabel(/Как с вами связаться/).fill("ani@example.com");
await a.getByLabel("Для чего").selectOption("packaging");
await a.getByLabel("Сколько кодов").fill("500");
await a.locator('input[type=file]').setInputFiles(new URL("./photo.jpg", import.meta.url).pathname);
await a.getByLabel("Пожелания").fill("Тёплые цвета, как свежий хлеб. Код на коробке с тортом.");
await a.getByRole("radio", { name: /Про/ }).click();
await shot(a, "b-390-form");
await a.getByRole("button", { name: /Оплатить и отправить — \$199/ }).click();
await a.waitForURL(/\/brand\/\w+/);
await a.waitForSelector("text=Дизайнер работает над заказом");
const orderUrl = a.url();
await shot(a, "b-390-order-client");

const n = await mk(1280);
await n.goto(B + "/login?next=/brand");
await n.getByRole("button", { name: /Наре/ }).click();
await n.waitForSelector("text=Заказы брендов");
await n.getByRole("link", { name: /Ani Bakery/ }).click();
await n.getByPlaceholder("Сообщение", { exact: true }).fill("Здравствуйте! Беру заказ, к вечеру пришлю варианты.");
await n.getByRole("button", { name: "Отправить", exact: true }).click();
await n.waitForSelector("text=Беру заказ");
ok(await n.locator("text=В работе").count() > 0, "reply moves order to In progress");
await n.getByRole("tab", { name: "Фон", exact: true }).click();
await n.getByRole("radio", { name: "Крафт", exact: true }).click();
await n.getByRole("tab", { name: "Форма", exact: true }).click();
await n.getByRole("radio", { name: "Мягкие", exact: true }).click();
await n.waitForFunction(() => /Код читается/.test(document.body.innerText), null, { timeout: 30000 });
await n.getByLabel("Пара слов к дизайну").fill("Крафт и мягкие точки — как упаковка пекарни. Логотип в центре.");
await n.getByRole("button", { name: "Отправить дизайн клиенту" }).last().click();
await n.waitForSelector("text=Отправлено — клиент увидит дизайн");
await shot(n, "b-1280-designer");

await a.goto(orderUrl, { waitUntil: "networkidle" });
await a.waitForSelector("text=Дизайн готов");
ok(await a.locator("text=Беру заказ").count() === 1, "client sees designer message");
await a.getByRole("button", { name: /Создать код в этом дизайне/ }).click();
await a.waitForSelector("text=Ani Bakery 1");
await a.getByRole("button", { name: /Создать код в этом дизайне/ }).click();
await a.waitForSelector("text=Создано кодов: 2");
await a.getByRole("button", { name: /Всё нравится/ }).click();
await a.waitForSelector("text=Готово");
await shot(a, "b-390-order-done");
// созданный код — уже оплачен
await a.getByRole("link", { name: "Настроить" }).click();
await a.getByRole("tab", { name: /Вид кода/ }).click();
await a.waitForFunction(() => /Код читается/.test(document.body.innerText), null, { timeout: 30000 });
const [d] = await Promise.all([a.waitForEvent("download", { timeout: 15000 }).catch(() => null), a.getByRole("button", { name: /Скачать PNG/ }).click()]);
ok(!!d, "brand code downloads without extra payment");
console.log("errors:", errors.length ? errors : "none");
await browser.close();
