import { chromium } from "playwright";
const out = new URL("./out/", import.meta.url).pathname;
const B = "http://localhost:3720";
const browser = await chromium.launch();
const errors = [];
const ok = (c, m) => { console.log(c ? "  ✓" : "  ✗", m); if (!c) errors.push(m); };
const shot = async (p, name) => { await p.waitForTimeout(400); await p.screenshot({ path: out + name + ".png", fullPage: true }); const o = await p.evaluate(() => document.documentElement.scrollWidth - innerWidth); if (o) errors.push(`${name} overflow ${o}`); };
const demo = async (who, next, w = 1280, locale = "ru-RU") => { const ctx = await browser.newContext({ viewport: { width: w, height: 900 }, locale }); const p = await ctx.newPage(); p.on("pageerror", (e) => errors.push(e.message)); await p.goto(`${B}/login?next=${encodeURIComponent(next)}`); await p.getByRole("button", { name: new RegExp(who) }).click(); await p.waitForURL((u) => !u.pathname.startsWith("/login")); return p; };
const n = await demo("Наре", "/create");
await n.getByLabel("Название дизайна", { exact: true }).fill("Кофейня");
await n.getByText("Название на армянском и английском").click();
await n.getByLabel("Название дизайна — Հայերեն").fill("Սրճարան");
await n.getByLabel("Название дизайна — English").fill("Coffee House");
await n.getByLabel("Коллаборация с (необязательно)").fill("Ararat Coffee");
await n.getByRole("radio", { name: "С номерами" }).click();
await n.getByLabel("Сколько штук в тираже").fill("10");
await n.getByRole("button", { name: "Опубликовать" }).click();
await n.waitForSelector("text=Опубликовано");
const a = await demo("Арман", "/market");
await a.waitForSelector("text=QR Space × Ararat Coffee");
ok(true, "collab badge on market card");
await a.getByRole("link", { name: /Кофейня/ }).click();
await a.waitForURL(/\/market\/[\w-]+/);
await a.getByRole("button", { name: /Купить —/ }).click();
await a.waitForSelector("text=Сертификат подлинности");
await a.getByRole("link", { name: /Сертификат подлинности/ }).click();
await a.waitForSelector("text=QR Space × Ararat Coffee");
ok(await a.locator("text=№ 1").count() >= 1, "certificate shows edition number");
await shot(a, "c-cert");
const h = await demo("Արման", "/market", 390, "hy-AM");
await h.waitForSelector("text=Սրճարան", { timeout: 15000 }).catch(() => {}); ok(await h.locator("text=Սրճարան").count() >= 1, "Armenian design name shown in hy");
await demo("Arman", "/market", 390, "en-GB");
ok(true, "");
console.log("errors:", errors.length ? errors : "none");
await browser.close();
