import fs from "node:fs";
import { chromium } from "playwright";
const out = new URL("./out/", import.meta.url).pathname;
const B = "http://localhost:3720";
const browser = await chromium.launch();
const errors = [];
const ok = (c, m) => { console.log(c ? "  ✓" : "  ✗", m); if (!c) errors.push(m); };
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, locale: "ru-RU", acceptDownloads: true });
const p = await ctx.newPage();
p.on("pageerror", (e) => errors.push(e.message));
p.on("console", (m) => m.type() === "error" && errors.push(m.text()));
await p.goto(B + "/login?next=/");
await p.getByRole("button", { name: /Лилит/ }).click();
await p.waitForURL(B + "/");
await p.getByLabel("Адрес сайта").fill("example.com/live");
await p.getByRole("tab", { name: "Фон", exact: true }).click();
await p.getByRole("radio", { name: "Космос", exact: true }).click();
await p.getByRole("tab", { name: "Форма", exact: true }).click();
await p.getByRole("radio", { name: "Круги", exact: true }).click();
await p.waitForFunction(() => /Код читается/.test(document.body.innerText), null, { timeout: 30000 });
await p.getByRole("button", { name: /Видео-код|Живой код/ }).click();
await p.waitForSelector("text=К оплате: $5");
const [d] = await Promise.all([p.waitForEvent("download", { timeout: 30000 }), p.getByRole("button", { name: /Оплатить и скачать/ }).click()]);
const file = out + "live." + d.suggestedFilename().split(".").pop();
await d.saveAs(file);
const size = fs.statSync(file).size;
console.log("  file:", d.suggestedFilename(), Math.round(size / 1024), "KB");
ok(/-live\.(mp4|webm)$/.test(d.suggestedFilename()) && size > 30_000, "live video downloaded");
// кадр из середины видео читается
const v = await browser.newPage();
await v.setContent(`<video id=v muted playsinline src="data:video/${file.endsWith("mp4") ? "mp4" : "webm"};base64,${fs.readFileSync(file).toString("base64")}"></video>`);
const frame = await v.evaluate(async () => {
  const el = document.getElementById("v");
  await new Promise((r) => (el.readyState >= 1 ? r() : (el.onloadedmetadata = r)));
  el.currentTime = 2;
  await new Promise((r) => (el.onseeked = r));
  const c = document.createElement("canvas");
  c.width = c.height = 600;
  c.getContext("2d").drawImage(el, 0, 0, 600, 600);
  return c.toDataURL("image/png");
});
fs.writeFileSync(out + "live-frame.png", Buffer.from(frame.split(",")[1], "base64"));
console.log("errors:", errors.length ? errors : "none");
await browser.close();
