import { chromium } from "playwright";
const out = new URL("./out/", import.meta.url).pathname;
const B = "http://localhost:3720";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, locale: "ru-RU" });
const p = await ctx.newPage();
const errors = [];
p.on("pageerror", (e) => errors.push(e.message));
await p.goto(B + "/login");
await p.getByRole("button", { name: /Арман/ }).click();
await p.waitForSelector("text=Wi");
await p.getByRole("link", { name: /Wi/ }).click();
await p.getByRole("tab", { name: /Вид кода/ }).click();
await p.waitForSelector("text=Код читается", { timeout: 30000 });
console.log("scan ok in look tab");
await p.getByRole("radio", { name: "Круги" }).click();
await p.waitForSelector("text=Сохранено", { timeout: 10000 });
await p.reload();
await p.getByRole("tab", { name: /Вид кода/ }).click();
console.log("dots persisted:", await p.getByRole("radio", { name: "Круги" }).getAttribute("aria-checked"));
await p.waitForSelector("text=Код читается", { timeout: 30000 });
console.log("still reads");
// армянский, телефон
const m = await browser.newContext({ viewport: { width: 390, height: 800 }, locale: "hy-AM" });
const q = await m.newPage();
await q.goto(B + "/login");
await q.getByRole("button", { name: /Արման/ }).click();
await q.waitForURL(/codes$/); await q.waitForSelector("text=Котёл");
await q.getByRole("link", { name: /Котёл/ }).last().click();
await q.getByRole("tab", { name: /Ով է տեսնում/ }).click();
await q.waitForTimeout(500);
console.log("hy overflow", await q.evaluate(() => document.documentElement.scrollWidth - innerWidth));
await q.screenshot({ path: out + "hy-access.png", fullPage: true });
console.log("errors", errors);
await browser.close();
