import { chromium } from "playwright";
const out = new URL("./out/", import.meta.url).pathname;
const B = "http://localhost:3720";
const browser = await chromium.launch();
const errors = [];
const ctx = await browser.newContext({ viewport: { width: 390, height: 900 }, locale: "ru-RU", acceptDownloads: true });
const p = await ctx.newPage();
p.on("pageerror", (e) => errors.push(e.message));
p.on("console", (m) => m.type() === "error" && !/401|409/.test(m.text()) && errors.push(m.text()));
const ok = (c, m) => { console.log(c ? "  ✓" : "  ✗", m); if (!c) errors.push(m); };
const shot = async (name) => { await p.waitForTimeout(300); await p.screenshot({ path: out + name + ".png", fullPage: true }); };
const ready = () => p.waitForFunction(() => /Код читается/.test(document.body.innerText), null, { timeout: 30000 });
const dl = async (fn) => { const [d] = await Promise.all([p.waitForEvent("download", { timeout: 15000 }), fn()]); return d.suggestedFilename(); };

await p.goto(B + "/", { waitUntil: "networkidle" });
await p.getByLabel("Адрес сайта").fill("example.com/one");
await ready();
await p.getByRole("button", { name: /Скачать PNG/ }).click();
// Без входа — окно входа поверх страницы; после демо-входа скачивание продолжается само (настроенное не теряется)
await p.getByRole("dialog", { name: "Войдите, чтобы скачать" }).waitFor();
ok(true, "guest must sign in to download (login window)");
await p.getByRole("dialog").getByRole("button", { name: /Лилит/ }).click();
await p.waitForSelector("text=Ваш первый простой код — бесплатно");
ok((await p.getByLabel("Адрес сайта").inputValue()) === "example.com/one", "after sign-in the address is still there");
await shot("p-free");
ok((await dl(() => p.getByRole("button", { name: "Скачать бесплатно" }).click())) === "qr-code.png", "first simple code downloads free");
ok((await dl(() => p.getByRole("button", { name: /Скачать SVG/ }).click())) === "qr-code.svg", "same code again — no payment asked");
await p.getByLabel("Адрес сайта").fill("example.com/two");
await ready();
await p.getByRole("button", { name: /Скачать PNG/ }).click();
await p.waitForSelector("text=К оплате: $1");
ok((await dl(() => p.getByRole("button", { name: /Оплатить и скачать — \$1/ }).click())) === "qr-code.png", "second simple code: $1");
await p.getByRole("tab", { name: "Форма", exact: true }).click();
await p.getByRole("radio", { name: "Звёзды", exact: true }).click();
await ready();
ok(await p.locator("text=Красивый код").count() === 1, "styled tier shown");
await p.getByRole("button", { name: /Скачать PNG/ }).click();
await p.waitForSelector("text=К оплате: $1");
ok(true, "styled generator code: $1 (owner 09.10: every code $1)");
await shot("p-styled");
// код с памятью: простой (первый бесплатный у Армана), потом красивее — доплата разницы $4
await p.goto(B + "/login?next=/codes");
await p.getByRole("button", { name: /Арман/ }).click();
await p.waitForURL(/codes$/);
await p.getByRole("button", { name: /Новый код/ }).click();
await p.getByLabel("Название кода").fill("Тест оплаты");
await p.getByRole("button", { name: "Создать" }).click();
await p.waitForURL(/\/codes\/\w+/);
await p.getByRole("tab", { name: /Вид кода/ }).click();
await ready();
await p.getByRole("button", { name: /Скачать PNG/ }).click();
await p.waitForSelector("text=Ваш первый простой код — бесплатно");
await dl(() => p.getByRole("button", { name: "Скачать бесплатно" }).click());
// Скачанный код — вид закреплён (владелец 08.10.2026): настроек нет, сервер вид не меняет, скачать снова — бесплатно
await p.waitForSelector("text=Вид закреплён");
ok((await p.getByRole("tab", { name: "Форма", exact: true }).count()) === 0, "downloaded code: style settings are gone");
const codeId = p.url().split("/").pop().split("#")[0];
const st = await p.evaluate(async (id) => {
  const c = await fetch(`/api/codes/${id}`).then((r) => r.json());
  return fetch(`/api/codes/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ style: { ...c.style, dot: "star" } }) }).then((r) => r.status);
}, codeId);
ok(st === 409, `server refuses to change a locked look (${st})`);
ok((await dl(() => p.getByRole("button", { name: /Скачать PNG/ }).click())).endsWith(".png"), "the same code downloads again for free");
console.log("errors:", errors.length ? errors : "none");
await browser.close();
