import { chromium } from "playwright";
const out = new URL("./out/", import.meta.url).pathname;
const B = "http://localhost:3720";
const browser = await chromium.launch();
const errors = [];
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, locale: "ru-RU" });
await ctx.addInitScript(() => { window.print = () => { window.__printed = (window.__printed ?? 0) + 1; }; });
const p = await ctx.newPage();
p.on("pageerror", (e) => errors.push(e.message));
p.on("console", (m) => m.type() === "error" && errors.push(m.text()));
const ok = (c, m) => { console.log(c ? "  ✓" : "  ✗", m); if (!c) errors.push(m); };
await p.goto(B + "/login?next=/codes/print");
await p.getByRole("button", { name: /Арман/ }).click();
await p.waitForURL(/print/);
await p.waitForSelector("text=Какие коды");
await p.getByRole("button", { name: /Создать набор/ }).click();
await p.waitForSelector("text=Метка 10");
await p.waitForTimeout(500);
ok((await p.locator("text=Наклеек всего: 10").count()) === 1, "set of 10 selected");
ok((await p.locator("[aria-label^='Лист']").count()) === 1, "10 stickers of 4 cm fit on one A4");
await p.screenshot({ path: out + "s-1280-print.png", fullPage: true });
await p.getByRole("button", { name: /Печатать/ }).click();
await p.waitForSelector("text=К оплате: $9");
ok(true, "first simple free, 9 × $1 = $9");
await p.getByRole("button", { name: "Оплатить и печатать" }).click();
await p.waitForFunction(() => window.__printed === 1);
ok(true, "print opened after payment");
await p.getByRole("button", { name: /Печатать/ }).click();
await p.waitForFunction(() => window.__printed === 2);
ok(true, "paid — prints again without paying");
// все мои коды, 3 см, по 2 → несколько листов; PDF как при печати
await p.getByRole("checkbox").first().waitFor();
await p.getByRole("radio", { name: "3 см" }).click();
await p.getByLabel("Сколько каждой").fill("3");
await p.waitForTimeout(500);
const sheets = await p.locator("[aria-label^='Лист']").count();
console.log("  sheets:", sheets, await p.locator("text=/Наклеек всего/").innerText());
await p.emulateMedia({ media: "print" });
await p.pdf({ path: out + "s-sheet.pdf", format: "A4", printBackground: true, preferCSSPageSize: true });
const pdfPages = (await import("node:fs")).readFileSync(out + "s-sheet.pdf", "latin1").match(/\/Type\s*\/Page[^s]/g)?.length;
ok(pdfPages === sheets, `PDF pages (${pdfPages}) = sheets (${sheets})`);
console.log("errors:", errors.length ? errors : "none");
await browser.close();
