import { chromium } from "playwright";
const out = new URL("./out/", import.meta.url).pathname;
const B = "http://localhost:3720";
const browser = await chromium.launch();
const errors = [];
const mk = async (w) => {
  const ctx = await browser.newContext({ viewport: { width: w, height: 900 }, locale: "ru-RU" });
  const page = await ctx.newPage();
  page.on("pageerror", (e) => errors.push(`${w} ${e.message}`));
  page.on("console", (m) => m.type() === "error" && errors.push(`${w} ${m.text()}`));
  return page;
};
const shot = async (p, name) => { await p.waitForTimeout(400); await p.screenshot({ path: out + name + ".png", fullPage: true }); const o = await p.evaluate(() => document.documentElement.scrollWidth - innerWidth); console.log(name, o ? `OVERFLOW ${o}` : "ok"); };
const ok = (c, m) => { console.log(c ? "  ✓" : "  ✗", m); if (!c) errors.push(m); };
const g = await mk(390);
await g.goto(B + "/shop", { waitUntil: "networkidle" });
await shot(g, "h-390-guest");
const p = await mk(1280);
await p.goto(B + "/login?next=/shop");
await p.getByRole("button", { name: /Арман/ }).click();
await p.waitForSelector("text=Какой код");
await p.getByLabel("Какой код").selectOption({ label: "Бублик" });
await shot(p, "h-1280-shop");
await p.locator("li:has-text('Жетон для питомца')").getByRole("button", { name: "Заказать" }).click();
await p.getByRole("radio", { name: "Косточка" }).click();
await p.getByLabel("Имя получателя").fill("Арман");
await p.getByLabel("Телефон").fill("+374 99 123456");
await p.getByLabel("Город").fill("Ереван");
await p.getByLabel("Улица, дом, квартира").fill("Абовяна 1, кв. 5");
await p.getByRole("button", { name: /Оплатить и заказать — \$10/ }).click();
await p.waitForSelector("text=Заказ принят");
ok(await p.locator("text=Мои заказы товаров").count() === 1, "order listed");
ok(await p.locator("text=Жетон для питомца · Косточка × 1").count() === 1, "variant saved");
await shot(p, "h-1280-ordered");
const m = await mk(390);
await m.goto(B + "/login?next=/shop");
await m.getByRole("button", { name: /Арман/ }).click();
await m.waitForSelector("text=Мои заказы товаров");
await shot(m, "h-390-shop");
console.log("errors:", errors.length ? errors : "none");
await browser.close();
